name: Sandwich
favicon: null
layout_spectrum: 0.696791
typography_spectrum: 0.63868
title: Sandwich.farm
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C89098'
    - '#000000'
    - '#588098'
    - '#000000'
    - '#E0B8B8'
  brandStrength: 0.05152
  lightness: 0.546453
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
