analytics: {}
color:
  brandColors:
    - '#C89098'
    - '#000000'
    - '#588098'
    - '#000000'
    - '#E0B8B8'
  brandStrength: 0.05152
  lightness: 0.546453
  rhythmicContrast: 0.171453
  saturation: 0.5
cta: {}
layout_spectrum: 0.696791
name: Sandwich
opengraph: {}
purpose: []
typography_spectrum: 0.63868
