name: Sandwich
favicon: null
layout_spectrum: 0.21270105615258217
typography_spectrum: 0.8442523465491831
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6747243867721409
  lightness: 0.31008736696094275
  saturation: 0.8171869276557118
  rhythmicContrast: 0.9209079537540674
purpose: []
