name: Sandwich
favicon: null
layout_spectrum: 0.23902
typography_spectrum: 0.63868
title: Sandwich.farm
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C8C0B0'
    - '#625122'
    - '#A09068'
    - '#D0B878'
    - '#E8D8A8'
  brandStrength: 0.193412
  lightness: 0.5
  saturation: 0.508446
  rhythmicContrast: 0.247466
purpose: []
