name: Sandwich
favicon: null
layout_spectrum: 0.94093
typography_spectrum: 0.29352
title: Sandwich.farm
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C89098'
    - '#000000'
    - '#588098'
    - '#000000'
    - '#E0B8B8'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
