analytics: {}
color:
  brandColors:
    - '#C8C0B0'
    - '#625122'
    - '#A09068'
    - '#D0B878'
    - '#E8D8A8'
  brandStrength: 0.193412
  lightness: 0.5
  rhythmicContrast: 0.247466
  saturation: 0.508446
cta: {}
layout_spectrum: 0.23902
name: Sandwich
opengraph: {}
purpose: []
typography_spectrum: 0.63868
